package api;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.github.javafaker.Faker;
import entity.ResponseBody;
import io.restassured.RestAssured;
import io.restassured.http.ContentType;
import io.restassured.response.Response;
import lombok.Getter;
import org.codehaus.groovy.transform.SourceURIASTTransformation;
import org.junit.Assert;
import org.junit.Test;
import utilities.Config;
import utilities.StudyMateAuthToken;

import java.util.HashMap;
import java.util.Map;

import static io.restassured.RestAssured.*;

public class day3 {
    @Getter
    private static ResponseBody responseBody;
    @Test
    public  void test_1_createNewProduct () throws JsonProcessingException {
        String token = CashwiseToken.getAuthorized();
        String url = Config.getProperty("baseURLCashwise") + "/api/myaccount/products";
        Faker faker = new Faker();
        String productTitle = faker.commerce().productName();
        double productPrice = faker.number().numberBetween(100,5600);
        int serviceId = 2;
        int categoryId = 805;
        String description = productTitle + "company";

        Map<String, Object> requestBody = new HashMap<>();
        requestBody.put("product_title", productTitle);
        requestBody.put("product_price", productPrice);
        requestBody.put("service_type_id", serviceId);
        requestBody.put("category_id",categoryId);
        requestBody.put("product_description",description);

        Response response = RestAssured.given()
                .auth().oauth2(token)
                .contentType(ContentType.JSON)
                .body(requestBody)
                .post(url);

        response.prettyPrint();

        String productID = response.jsonPath().getString("product_id");

        System.out.println(productID);
        System.out.print("================================");
        String path = "/api/myaccount/products";
        // get exact product you generated by id
        //use get request  than with json path finder you have to egt product title
        runGET (path,productID);
    }

    public static void runGET(String path, String id) throws JsonProcessingException {

        String token = CashwiseToken.getAuthorized();
        baseURI = (Config.getProperty("baseURLCashwise"));
        basePath = path;
        Response response = given()
                .auth()
                .oauth2(token)
                .when()
                .get(baseURI + basePath+ "/" +id);
      response.prettyPrint();
      String actualProductTitle = response.jsonPath().getString("product_title");
      String actualProductPrice = response.jsonPath().getString("product_price");
      String actualProductDescription = response.jsonPath().getString("product_description");

    }


}
